using DanielsDojo.Domain.Identity;

namespace DanielsDojo.Domain.Media;

/// <summary>
/// One authorisation to write exactly one blob.
/// </summary>
/// <remarks>
/// <para>
/// The session is what the short-lived credential is minted against, and it is the only record
/// of an in-flight upload. Nothing about the lesson changes until finalisation verifies the
/// stored object, so an abandoned, expired, or hostile attempt cannot disturb content that is
/// currently serving.
/// </para>
/// <para>
/// The blob name is generated by the server from the target and a fresh identifier. A client
/// never chooses where its bytes land, so a caller cannot aim an upload at another lesson's
/// object or escape the container prefix.
/// </para>
/// </remarks>
public sealed class MediaUploadSession
{
    /// <summary>Application-owned primary key. Also the correlation identifier.</summary>
    public Guid Id { get; set; }

    /// <summary>What the upload is for.</summary>
    public MediaPurpose Purpose { get; set; }

    /// <summary>Course this upload belongs to. Always set, so ownership is checkable.</summary>
    public Guid CourseId { get; set; }

    /// <summary>Lesson targeted, for lesson-scoped purposes.</summary>
    public Guid? LessonId { get; set; }

    /// <summary>Admin who requested the session. Immutable local identifier, never an email.</summary>
    public Guid RequestedByUserId { get; set; }

    /// <summary>Storage container the blob is written to.</summary>
    public string ContainerName { get; set; } = string.Empty;

    /// <summary>Server-generated blob name. A client never supplies this.</summary>
    public string BlobName { get; set; } = string.Empty;

    /// <summary>Original file name as reported by the client, for operator display only.</summary>
    public string? OriginalFileName { get; set; }

    /// <summary>Size the client declared, in bytes. Bounded before authorisation.</summary>
    public long DeclaredSizeBytes { get; set; }

    /// <summary>Content type the client declared. Checked against the allowlist.</summary>
    public string DeclaredContentType { get; set; } = string.Empty;

    /// <summary>
    /// Whether this attempt is replacing an existing current source. A replacement never
    /// promotes itself over the incumbent until it is fully verified.
    /// </summary>
    public bool IsReplacement { get; set; }

    /// <summary>Lifecycle state.</summary>
    public MediaUploadStatus Status { get; set; } = MediaUploadStatus.Requested;

    /// <summary>Which provider wiring authorised this session.</summary>
    public ProviderMode ProviderMode { get; set; }

    /// <summary>When the write authorisation stops being valid, stored UTC.</summary>
    public DateTimeOffset ExpiresAtUtc { get; set; }

    /// <summary>When finalisation succeeded, stored UTC.</summary>
    public DateTimeOffset? CompletedAtUtc { get; set; }

    /// <summary>Stable internal failure category. Never a raw provider body.</summary>
    public string? FailureCode { get; set; }

    /// <summary>Creation instant, stored UTC.</summary>
    public DateTimeOffset CreatedAtUtc { get; set; }

    /// <summary>Last modification instant, stored UTC.</summary>
    public DateTimeOffset UpdatedAtUtc { get; set; }

    /// <summary>SQL Server rowversion concurrency token.</summary>
    public byte[] RowVersion { get; set; } = [];

    /// <summary>The requesting Admin.</summary>
    public User? RequestedByUser { get; set; }

    /// <summary>Whether the session may still accept a finalisation attempt at the given time.</summary>
    public bool IsOpenAt(DateTimeOffset now) =>
        Status is MediaUploadStatus.Requested or MediaUploadStatus.Uploading && ExpiresAtUtc > now;
}
