// <auto-generated />
using System;
using DanielsDojo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DanielsDojo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DanielsDojoDbContext))]
    partial class DanielsDojoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DanielsDojo.Domain.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("IX_AuditLogs_ActorUserId");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_AuditLogs_OccurredAtUtc");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("IX_AuditLogs_TargetType_TargetId");

                    b.ToTable("AuditLogs", "audit");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ImageAltText")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ImageStorageKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IncludedInMembership")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("IncludedInMembership")
                        .HasDatabaseName("IX_Courses_IncludedInMembership");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Courses_Slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Courses_Status");

                    b.ToTable("Courses", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Courses_Level", "[Level] IN ('Beginner', 'Intermediate', 'Advanced', 'AllLevels')");

                            t.HasCheckConstraint("CK_Courses_Status", "[Status] IN ('Draft', 'Published', 'Archived')");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.CourseInstructor", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("CourseId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_CourseInstructors_UserId");

                    b.ToTable("CourseInstructors", "catalog");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.CourseSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasAlternateKey("CourseId", "Id")
                        .HasName("AK_CourseSections_CourseId_Id");

                    b.HasIndex("CourseId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_CourseSections_CourseId_SortOrder");

                    b.ToTable("CourseSections", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_CourseSections_Status", "[Status] IN ('Draft', 'Published', 'Archived')");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.CourseTag", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_CourseTags_TagId");

                    b.ToTable("CourseTags", "catalog");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyMarkdown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int?>("EstimatedDurationSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("IsPreview")
                        .HasColumnType("bit");

                    b.Property<string>("LessonType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Summary")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Lessons_Status");

                    b.HasIndex("CourseId", "CourseSectionId");

                    b.HasIndex("CourseId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Lessons_CourseId_Slug");

                    b.HasIndex("CourseSectionId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_Lessons_CourseSectionId_SortOrder");

                    b.ToTable("Lessons", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Lessons_EstimatedDurationSeconds_NonNegative", "[EstimatedDurationSeconds] IS NULL OR [EstimatedDurationSeconds] >= 0");

                            t.HasCheckConstraint("CK_Lessons_LessonType", "[LessonType] IN ('Video', 'Article')");

                            t.HasCheckConstraint("CK_Lessons_SortOrder_NonNegative", "[SortOrder] >= 0");

                            t.HasCheckConstraint("CK_Lessons_Status", "[Status] IN ('Draft', 'Published', 'Archived')");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.LessonResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobObjectName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("BlobObjectName")
                        .IsUnique()
                        .HasDatabaseName("UX_LessonResources_BlobObjectName")
                        .HasFilter("[BlobObjectName] IS NOT NULL");

                    b.HasIndex("LessonId", "SortOrder")
                        .HasDatabaseName("IX_LessonResources_LessonId_SortOrder");

                    b.ToTable("LessonResources", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_LessonResources_PublishedRequiresBlob", "[Status] <> 'Published' OR [BlobObjectName] IS NOT NULL");

                            t.HasCheckConstraint("CK_LessonResources_SizeBytes_NonNegative", "[SizeBytes] >= 0");

                            t.HasCheckConstraint("CK_LessonResources_Status", "[Status] IN ('Draft', 'Published', 'Archived')");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.LessonVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MuxAssetId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MuxPlaybackId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .IsUnique()
                        .HasDatabaseName("UX_LessonVideos_LessonId");

                    b.HasIndex("MuxAssetId")
                        .IsUnique()
                        .HasDatabaseName("UX_LessonVideos_MuxAssetId")
                        .HasFilter("[MuxAssetId] IS NOT NULL");

                    b.HasIndex("MuxPlaybackId")
                        .IsUnique()
                        .HasDatabaseName("UX_LessonVideos_MuxPlaybackId")
                        .HasFilter("[MuxPlaybackId] IS NOT NULL");

                    b.ToTable("LessonVideos", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_LessonVideos_DurationSeconds_NonNegative", "[DurationSeconds] IS NULL OR [DurationSeconds] >= 0");

                            t.HasCheckConstraint("CK_LessonVideos_Status", "[Status] IN ('Pending', 'Preparing', 'Ready', 'Errored', 'Disabled')");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_Tags_NormalizedName");

                    b.ToTable("Tags", "catalog");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.Entitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("EndsAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("GrantReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("OrderItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_Entitlements_OrderItemId")
                        .HasFilter("[OrderItemId] IS NOT NULL");

                    b.HasIndex("RevokedByUserId");

                    b.HasIndex("SubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Entitlements_SubscriptionId")
                        .HasFilter("[SubscriptionId] IS NOT NULL");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_Entitlements_UserId_Status");

                    b.HasIndex("UserId", "CourseId", "Status")
                        .HasDatabaseName("IX_Entitlements_UserId_CourseId_Status");

                    b.ToTable("Entitlements", "commerce", t =>
                        {
                            t.HasCheckConstraint("CK_Entitlements_CourseScopeRequiresCourse", "[Scope] <> 'Course' OR [CourseId] IS NOT NULL");

                            t.HasCheckConstraint("CK_Entitlements_EndsAfterStarts", "[EndsAtUtc] IS NULL OR [EndsAtUtc] >= [StartsAtUtc]");

                            t.HasCheckConstraint("CK_Entitlements_ManualSource", "[Source] <> 'Manual' OR ([SubscriptionId] IS NULL AND [OrderItemId] IS NULL)");

                            t.HasCheckConstraint("CK_Entitlements_MembershipScopeForbidsCourse", "[Scope] <> 'AllMembershipCourses' OR [CourseId] IS NULL");

                            t.HasCheckConstraint("CK_Entitlements_PurchaseSource", "[Source] <> 'Purchase' OR ([OrderItemId] IS NOT NULL AND [SubscriptionId] IS NULL)");

                            t.HasCheckConstraint("CK_Entitlements_Scope", "[Scope] IN ('AllMembershipCourses', 'Course')");

                            t.HasCheckConstraint("CK_Entitlements_Source", "[Source] IN ('Subscription', 'Purchase', 'Manual')");

                            t.HasCheckConstraint("CK_Entitlements_Status", "[Status] IN ('Active', 'Revoked', 'Expired')");

                            t.HasCheckConstraint("CK_Entitlements_SubscriptionSource", "[Source] <> 'Subscription' OR ([SubscriptionId] IS NOT NULL AND [OrderItemId] IS NULL)");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("StripeProductId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Offers_Code");

                    b.HasIndex("CourseId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Offers_Status");

                    b.HasIndex("StripeProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_Offers_StripeProductId")
                        .HasFilter("[StripeProductId] IS NOT NULL");

                    b.ToTable("Offers", "commerce", t =>
                        {
                            t.HasCheckConstraint("CK_Offers_CourseLifetimeRequiresCourse", "[Kind] <> 'CourseLifetime' OR [CourseId] IS NOT NULL");

                            t.HasCheckConstraint("CK_Offers_Kind", "[Kind] IN ('Membership', 'CourseLifetime')");

                            t.HasCheckConstraint("CK_Offers_MembershipForbidsCourse", "[Kind] <> 'Membership' OR [CourseId] IS NULL");

                            t.HasCheckConstraint("CK_Offers_Status", "[Status] IN ('Draft', 'Active', 'Retired')");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("PaidAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("SubtotalMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StripeCheckoutSessionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_StripeCheckoutSessionId")
                        .HasFilter("[StripeCheckoutSessionId] IS NOT NULL");

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_StripePaymentIntentId")
                        .HasFilter("[StripePaymentIntentId] IS NOT NULL");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Orders_UserId_CreatedAtUtc");

                    b.ToTable("Orders", "commerce", t =>
                        {
                            t.HasCheckConstraint("CK_Orders_Amounts_NonNegative", "[SubtotalMinor] >= 0 AND [TaxMinor] >= 0 AND [TotalMinor] >= 0");

                            t.HasCheckConstraint("CK_Orders_Currency_Uppercase", "[Currency] = UPPER([Currency]) COLLATE Latin1_General_BIN2");

                            t.HasCheckConstraint("CK_Orders_Status", "[Status] IN ('Pending', 'Paid', 'Failed', 'PartiallyRefunded', 'Refunded', 'Disputed', 'ChargebackLost')");

                            t.HasCheckConstraint("CK_Orders_Total_Reconciles", "[TotalMinor] = [SubtotalMinor] + [TaxMinor]");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<long>("LineTotalMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OfferName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("UnitAmountMinor")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("IX_OrderItems_CourseId");

                    b.HasIndex("OfferId");

                    b.HasIndex("PriceId");

                    b.HasIndex("OrderId", "OfferId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderItems_OrderId_OfferId");

                    b.ToTable("OrderItems", "commerce", t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_Currency_Uppercase", "[Currency] = UPPER([Currency]) COLLATE Latin1_General_BIN2");

                            t.HasCheckConstraint("CK_OrderItems_LineTotal_Reconciles", "[LineTotalMinor] = [UnitAmountMinor] * [Quantity]");

                            t.HasCheckConstraint("CK_OrderItems_Quantity_One", "[Quantity] = 1");

                            t.HasCheckConstraint("CK_OrderItems_UnitAmountMinor_NonNegative", "[UnitAmountMinor] >= 0");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.PaymentDispute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("StripeChargeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StripeDisputeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PaymentDisputes_Status");

                    b.HasIndex("StripeDisputeId")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentDisputes_StripeDisputeId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("PaymentDisputes", "commerce", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentDisputes_AmountMinor_Positive", "[AmountMinor] > 0");

                            t.HasCheckConstraint("CK_PaymentDisputes_Currency_Uppercase", "[Currency] = UPPER([Currency]) COLLATE Latin1_General_BIN2");

                            t.HasCheckConstraint("CK_PaymentDisputes_ExactlyOneSource", "([OrderId] IS NOT NULL AND [SubscriptionId] IS NULL) OR ([OrderId] IS NULL AND [SubscriptionId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_PaymentDisputes_Status", "[Status] IN ('WarningNeedsResponse', 'NeedsResponse', 'UnderReview', 'Won', 'Lost', 'Closed')");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("BillingInterval")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("BillingIntervalCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RetiredAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("StripePriceId")
                        .IsUnique()
                        .HasDatabaseName("UX_Prices_StripePriceId")
                        .HasFilter("[StripePriceId] IS NOT NULL");

                    b.HasIndex("OfferId", "Status")
                        .HasDatabaseName("IX_Prices_OfferId_Status");

                    b.ToTable("Prices", "commerce", t =>
                        {
                            t.HasCheckConstraint("CK_Prices_AmountMinor_Positive", "[AmountMinor] > 0");

                            t.HasCheckConstraint("CK_Prices_BillingInterval", "[BillingInterval] IN ('OneTime', 'Month')");

                            t.HasCheckConstraint("CK_Prices_BillingIntervalCount_One", "[BillingIntervalCount] = 1");

                            t.HasCheckConstraint("CK_Prices_Currency_Uppercase", "[Currency] = UPPER([Currency]) COLLATE Latin1_General_BIN2");

                            t.HasCheckConstraint("CK_Prices_RetiredAfterEffective", "[RetiredAtUtc] IS NULL OR [RetiredAtUtc] >= [EffectiveFromUtc]");

                            t.HasCheckConstraint("CK_Prices_Status", "[Status] IN ('Draft', 'Active', 'Retired')");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<bool>("IsFullRefund")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("RequiresAccessReview")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StripeRefundId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("RequiresAccessReview")
                        .HasDatabaseName("IX_Refunds_RequiresAccessReview");

                    b.HasIndex("StripeRefundId")
                        .IsUnique()
                        .HasDatabaseName("UX_Refunds_StripeRefundId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Refunds", "commerce", t =>
                        {
                            t.HasCheckConstraint("CK_Refunds_AmountMinor_Positive", "[AmountMinor] > 0");

                            t.HasCheckConstraint("CK_Refunds_Currency_Uppercase", "[Currency] = UPPER([Currency]) COLLATE Latin1_General_BIN2");

                            t.HasCheckConstraint("CK_Refunds_ExactlyOneSource", "([OrderId] IS NOT NULL AND [SubscriptionId] IS NULL) OR ([OrderId] IS NULL AND [SubscriptionId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Refunds_Status", "[Status] IN ('Pending', 'Succeeded', 'Failed', 'Canceled')");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.StripeCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StripeCustomerId")
                        .IsUnique()
                        .HasDatabaseName("UX_StripeCustomers_StripeCustomerId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_StripeCustomers_UserId");

                    b.ToTable("StripeCustomers", "commerce");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("CanceledAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("CurrentPeriodEndUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("CurrentPeriodStartUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("FirstPaymentFailedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("GracePeriodEndsAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("TrialEndUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("TrialStartUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("PriceId");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Subscriptions_StripeSubscriptionId");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_Subscriptions_UserId_Status");

                    b.ToTable("Subscriptions", "commerce", t =>
                        {
                            t.HasCheckConstraint("CK_Subscriptions_PeriodOrdered", "[CurrentPeriodEndUtc] >= [CurrentPeriodStartUtc]");

                            t.HasCheckConstraint("CK_Subscriptions_Status", "[Status] IN ('Incomplete', 'Trialing', 'Active', 'PastDue', 'Unpaid', 'Paused', 'Canceled', 'IncompleteExpired')");

                            t.HasCheckConstraint("CK_Subscriptions_TrialOrdered", "[TrialStartUtc] IS NULL OR [TrialEndUtc] IS NULL OR [TrialEndUtc] >= [TrialStartUtc]");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("UX_WebhookEvents_Provider_ExternalEventId");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("IX_WebhookEvents_Status_NextAttemptAtUtc");

                    b.ToTable("WebhookEvents", "commerce", t =>
                        {
                            t.HasCheckConstraint("CK_WebhookEvents_AttemptCount_NonNegative", "[AttemptCount] >= 0");

                            t.HasCheckConstraint("CK_WebhookEvents_Status", "[Status] IN ('Received', 'Processing', 'Processed', 'Failed', 'Ignored')");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsAssignable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_Roles_NormalizedName");

                    b.ToTable("Roles", "identity");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("ExternalIssuer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalSubjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IdentityProvider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("IX_Users_NormalizedEmail");

                    b.HasIndex("ExternalIssuer", "ExternalSubjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_ExternalIssuer_ExternalSubjectId");

                    b.ToTable("Users", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Status", "[Status] IN ('Active', 'Disabled')");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.ToTable("UserRoles", "identity");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Learning.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("EnrolledAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("LastAccessedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("UX_Enrollments_UserId_CourseId");

                    b.ToTable("Enrollments", "learning");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Learning.LessonProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("LastPositionSeconds")
                        .HasColumnType("int");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId", "LessonId")
                        .IsUnique()
                        .HasDatabaseName("UX_LessonProgress_UserId_LessonId");

                    b.ToTable("LessonProgress", "learning", t =>
                        {
                            t.HasCheckConstraint("CK_LessonProgress_CompletedAfterStarted", "[CompletedAtUtc] IS NULL OR [CompletedAtUtc] >= [StartedAtUtc]");

                            t.HasCheckConstraint("CK_LessonProgress_CompletedRequiresStarted", "[CompletedAtUtc] IS NULL OR [StartedAtUtc] IS NOT NULL");

                            t.HasCheckConstraint("CK_LessonProgress_LastPositionSeconds_NonNegative", "[LastPositionSeconds] >= 0");
                        });
                });

            modelBuilder.Entity("DanielsDojo.Domain.Auditing.AuditLog", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.CourseInstructor", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Catalog.Course", "Course")
                        .WithMany("Instructors")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DanielsDojo.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.CourseSection", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Catalog.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.CourseTag", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Catalog.Course", "Course")
                        .WithMany("CourseTags")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DanielsDojo.Domain.Catalog.Tag", "Tag")
                        .WithMany("CourseTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.Lesson", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Catalog.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DanielsDojo.Domain.Catalog.CourseSection", "CourseSection")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId", "CourseSectionId")
                        .HasPrincipalKey("CourseId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Lessons_CourseSections_CourseId_CourseSectionId");

                    b.Navigation("Course");

                    b.Navigation("CourseSection");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.LessonResource", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Catalog.Lesson", "Lesson")
                        .WithMany("Resources")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.LessonVideo", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Catalog.Lesson", "Lesson")
                        .WithOne("Video")
                        .HasForeignKey("DanielsDojo.Domain.Catalog.LessonVideo", "LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.Entitlement", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Catalog.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DanielsDojo.Domain.Identity.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DanielsDojo.Domain.Commerce.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DanielsDojo.Domain.Identity.User", "RevokedByUser")
                        .WithMany()
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DanielsDojo.Domain.Commerce.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DanielsDojo.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("GrantedByUser");

                    b.Navigation("OrderItem");

                    b.Navigation("RevokedByUser");

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.Offer", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Catalog.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.Order", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.OrderItem", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Catalog.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DanielsDojo.Domain.Commerce.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DanielsDojo.Domain.Commerce.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DanielsDojo.Domain.Commerce.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Offer");

                    b.Navigation("Order");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.PaymentDispute", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Commerce.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DanielsDojo.Domain.Commerce.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.Price", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Commerce.Offer", "Offer")
                        .WithMany("Prices")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.Refund", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Commerce.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DanielsDojo.Domain.Commerce.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.StripeCustomer", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.Subscription", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Commerce.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DanielsDojo.Domain.Commerce.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DanielsDojo.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("Price");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Identity.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DanielsDojo.Domain.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DanielsDojo.Domain.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Learning.Enrollment", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Catalog.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DanielsDojo.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Learning.LessonProgress", b =>
                {
                    b.HasOne("DanielsDojo.Domain.Catalog.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DanielsDojo.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.Course", b =>
                {
                    b.Navigation("CourseTags");

                    b.Navigation("Instructors");

                    b.Navigation("Lessons");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.CourseSection", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.Lesson", b =>
                {
                    b.Navigation("Resources");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Catalog.Tag", b =>
                {
                    b.Navigation("CourseTags");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.Offer", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Commerce.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DanielsDojo.Domain.Identity.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
